### ISSUE TITLE
EEM - peripheral slot mapping

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_Kasli_Adapter#1]
According to current schematics, EEM - peripheral slot mapping is as follows:

| PS | EEM0 | EEM1 |
|----|------|------|
| 1  | 8    | -    |
| 2  | 0    | 1   |
| 3  | 3    | 2    |
| 4  | 5    | 4    |
| 5  | 7    | 6    |
| 6  | 10    | -    |
| 7  | 11    | -    |
| 8  | 9   | -    |

I'm just thinking if we could add a bit of elasticity here and make single-EEM slots convertible to double-EEM slots by using 4 LVDS switches, e.g. MAX14979E. This would give as configurations with up to 6 double-EEM slots or 4 double + 4 single, as it is currently.

EDIT: Fixed mapping according to #2

**Comment by gkasprow** [comment]
That was the initial idea :)

**Comment by gkasprow** [comment]
However, these switches have only 650MHz BW, so this would be limited to high-speed serial LVDS links like Grabber.

**Comment by gkasprow** [comment]
[TS3DV20812](https://www.ti.com/lit/ds/scds302/scds302.pdf?ts=1625237268479&ref_url=https%253A%252F%252Fwww.google.com%252F) would work

**Comment by kaolpr** [comment]
I'd suggest making first 4 slots permanent and group other 4 in 2 sets, i.e. we'd have PS 1-4 supporting dual EEM at all times and PS5-8 could be either:

* 4x single EEM or
* PS5 and PS7 as dual EEM and PS6 and PS8 with only power supply and I2C connectivity (what, after all can be used in same cases).

**Comment by kaolpr** [comment]
Additionally, if layout modifications are to be made, maybe we could consider keeping design more similar to Kasli, i.e. implementing the following mapping:

| Peripheral Slot | EEM0 | EEM1 |
|-----------------|------|------|
| 1               | 0    | 1    |
| 2               | 2    | 3    |
| 3               | 4    | 5    |
| 4               | 6    | 7    |
| 5               | 8    | (9)  |
| 6               | (9)  | -    |
| 7               | 10   | (11) |
| 8               | (11) | -    |

`(n)` means switched with LVDS mux

**Comment by mkiepiela** [comment]
The Kasli EEMs and DIOT peripherals slots mapping is as follows:

![image](https://user-images.githubusercontent.com/25741678/221404686-59f5261a-e757-422d-aded-ba2d97e41952.png)
