### ISSUE TITLE
Inconsistent port naming

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_Kasli_Adapter#2]
In schematics `EEM` ports are reffrred as `EXT`, same as in Kasli. However, actual mapping is messed up. `EXT0` on the adapter **is not** the same as `EXT0` on Kasli:

![messed_up_ext](https://user-images.githubusercontent.com/9166701/124590636-a9608f80-de5b-11eb-96a6-96a302108098.png)

**Comment by mkiepiela** [comment]
The module has been completely redesigned. Port nameing is now consistent with Kasli.

![image](https://user-images.githubusercontent.com/25741678/221404479-145c96f5-0b37-41aa-8ce8-fa2f7b358074.png)
