### ISSUE TITLE
Separation to radiator / fan

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_Kasli_Adapter#3]
Currently edge of PCB is disturbingly close to the fan. Bear in mind, that for Kasli 2 there is a fan that is taller than radiator in the Kasli model. To mitigate the risk of collision, please increase size of the cutout.
![image](https://user-images.githubusercontent.com/9166701/146006310-9ca88c5d-c72b-4b5f-ae5b-1a82a5d1bcd4.png)
Red line in the picture below shows position of the PCB according to the 3D model, note level of the fan:
![image](https://user-images.githubusercontent.com/9166701/146006895-de6a49ac-6592-4998-a107-d00405882790.png)

**Comment by mkiepiela** [comment]
Done.

![image](https://user-images.githubusercontent.com/25741678/221408274-3c339506-a47e-4f22-bbcc-42c07e8c802f.png)
