### ISSUE TITLE
Update document table

### ISSUE THREAD

**Issue by kaolpr** [sinara-hw/DIOT_Kasli_Adapter#4]
Gallery of tables for this project:

![image](https://user-images.githubusercontent.com/9166701/147269179-9c92bab4-2c63-44d1-9eeb-2bcd0f8b69ca.png)

![image](https://user-images.githubusercontent.com/9166701/147269246-7417d0a9-d663-40f4-a83d-076907cae652.png)

![image](https://user-images.githubusercontent.com/9166701/147269279-a124e58c-6204-4b51-97e7-1a19f085bc22.png)

**Comment by gkasprow** [comment]
good idea, let's replace CPCIS with DI/OT

**Comment by mkiepiela** [comment]
Done.
